image: alpine:latest

pages:
  stage: deploy
  tags:
    - docker
  script:
    - mkdir -p public
    - cp wizard.html public/index.html
    - cp index.html public/kbyg.html
  artifacts:
    paths:
      - public
  only:
    - main
