apiVersion: nvidia.com/v1alpha1
kind: DynamoGraphDeployment
metadata:
  name: dynamo-lab
spec:
  services:
    Frontend:
      componentType: frontend
      replicas: 1
      extraPodSpec:
        mainContainer:
          image: 10.100.11.173:5000/dynamo-mocker:1.0.0
          imagePullPolicy: Never
          env:
            - name: POD_UID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.uid

    Planner:
      componentType: planner
      replicas: 1
      extraPodSpec:
        mainContainer:
          image: 10.100.11.173:5000/dynamo-mocker:1.0.0
          imagePullPolicy: Never
          env:
            - name: POD_UID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.uid
          command:
            - python3
            - -m
            - dynamo.planner
          args:
            - --config
            - >-
              {"environment":"kubernetes","backend":"mocker",
               "throughput_adjustment_interval":30,
               "ttft":2000,"itl":200,
               "max_gpu_budget":-1,"no_correction":true,
               "prefill_engine_num_gpu":1,"decode_engine_num_gpu":1,
               "profile_results_dir":"/workspace/tests/planner/profiling_results/H200_TP1P_TP1D",
               "model_name":"nvidia/Llama-3.1-8B-Instruct-FP8"}

    PrefillWorker:
      componentType: worker
      subComponentType: prefill
      replicas: 1
      extraPodSpec:
        mainContainer:
          image: 10.100.11.173:5000/dynamo-mocker:1.0.0
          imagePullPolicy: Never
          workingDir: /workspace
          env:
            - name: POD_UID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.uid
          command:
            - python3
            - -m
            - dynamo.mocker
          args:
            - --model-path
            - nvidia/Llama-3.1-8B-Instruct-FP8
            - --model-name
            - nvidia/Llama-3.1-8B-Instruct-FP8
            - --speedup-ratio
            - "5.0"
            - --planner-profile-data
            - /workspace/tests/planner/profiling_results/H200_TP1P_TP1D
            - --is-prefill-worker

    DecodeWorker:
      componentType: worker
      subComponentType: decode
      replicas: 1
      extraPodSpec:
        mainContainer:
          image: 10.100.11.173:5000/dynamo-mocker:1.0.0
          imagePullPolicy: Never
          workingDir: /workspace
          env:
            - name: POD_UID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.uid
          command:
            - python3
            - -m
            - dynamo.mocker
          args:
            - --model-path
            - nvidia/Llama-3.1-8B-Instruct-FP8
            - --model-name
            - nvidia/Llama-3.1-8B-Instruct-FP8
            - --speedup-ratio
            - "5.0"
            - --planner-profile-data
            - /workspace/tests/planner/profiling_results/H200_TP1P_TP1D
